import fs, { readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { compileBSON } from "./bson-compiler.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outFolder = path.join(__dirname, "..", "generated");

async function listValidators() {
  const validatorsDir = path.join(__dirname, "..", "validators");
  let schemaFiles = [];

  // Read the directory contents using fs.readdir and filter for .json files
  try {
    const dirents = await fs.promises.readdir(validatorsDir, {
      withFileTypes: true,
    });

    for (const entry of dirents) {
      if (entry.isDirectory()) continue; // Skip directories

      let filePath = `${validatorsDir}/${entry.name}`;

      const collectionName = entry.name.split(".")[0];

      schemaFiles.push({
        collection: collectionName,
        schema: JSON.parse(readFileSync(filePath, "utf8")),
      });
    }
  } catch (error) {
    console.error("Error listing validators:", error.message);
  }

  return schemaFiles;
}

async function run() {
  const schemas = await listValidators();

  // Do something with the loaded JSON from files
  for (const { collection, schema } of schemas) {
    console.log(`Generating types for collection: ${collection}`);
    console.log(schema);
    const compiled = await compileBSON(schema, {
      bannerComment: [
        "/* eslint-disable */",
        "",
        "/**",
        "* This file was automatically generated by bson-schema-to-typescript.",
        "* https://www.npmjs.com/package/bson-schema-to-typescript",
        "*",
        "* Do not modify it by hand",
        "*/",
      ],
      enableConstEnums: true,
      ignoreMinAndMaxItems: false,
      strictIndexSignatures: false,
      unknownAny: true,
    });
    console.log(compiled);
    writeFileSync(path.join(outFolder, `${collection}.ts`), compiled);
  }
}

// Call to execute async functions in Node.js environment.
(async () => {
  try {
    await run();
  } catch (e) {
    console.error(e);
    process.exit(1);
  }

  process.exit(0);
})();
