const fs = require("fs");
const path = require("path");
const { compile } = require("json-schema-to-typescript");
const { execSync } = require("child_process");

const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const APP_ROOT = path.resolve(REPO_ROOT, "coreader-app");
const WORKER_ROOT = path.resolve(REPO_ROOT, "coreader-worker");
const DEFAULT_SCHEMAS_DIR = path.resolve(REPO_ROOT, "infra", "db", "schemas");
const DEFAULT_TS_OUTPUT = path.resolve(
  APP_ROOT,
  "lib",
  "db",
  "generated",
  "db-types.ts"
);
const DEFAULT_GO_OUTPUT = path.resolve(WORKER_ROOT, "dbtypes.go");
const DEFAULT_VALIDATORS_DIR = path.resolve(
  REPO_ROOT,
  "infra",
  "db",
  "validators"
);

const HEADER_COMMENT = `/**
 * This file was automatically generated by infra/db/scripts/generate-types.js.
 * Do not modify it by hand.
 */`;

const GO_HEADER = `/*
This file was automatically generated.

Do not modify it by hand
*/

package main`;

// Constants for special field handling
const SPECIAL_FIELDS = {
  ID: "_id",
};

const BSON_TYPE_MAP = {
  object: "object",
  array: "array",
  string: "string",
  integer: "int",
  number: "double",
  boolean: "bool",
};

const GO_TYPE_MAP = {
  string: "string",
  integer: "int",
  number: "float64",
  boolean: "bool",
};

/**
 * Normalizes a JSON schema for TypeScript generation by adding tsType hints.
 * Tracks whether the schema uses MongoDB ObjectId types.
 * @param {object} schema - The JSON schema to normalize
 * @returns {{schema: object, usesObjectId: boolean}}
 */
function normalizeSchema(schema) {
  let usesObjectId = false;

  const walk = (node) => {
    if (Array.isArray(node)) {
      return node.map(walk);
    }

    if (node === null || typeof node !== "object") {
      return node;
    }

    const normalized = { ...node };

    if (normalized.format === "objectId") {
      normalized.tsType = "ObjectId";
      usesObjectId = true;
    }

    if (normalized.format === "date-time") {
      normalized.tsType = "Date";
    }

    if (normalized.properties) {
      normalized.properties = Object.fromEntries(
        Object.entries(normalized.properties).map(([key, value]) => [
          key,
          walk(value),
        ])
      );
    }

    if (normalized.items) {
      normalized.items = walk(normalized.items);
    }

    ["$defs", "definitions"].forEach((defKey) => {
      if (normalized[defKey]) {
        normalized[defKey] = Object.fromEntries(
          Object.entries(normalized[defKey]).map(([key, value]) => [
            key,
            walk(value),
          ])
        );
      }
    });

    ["anyOf", "oneOf", "allOf"].forEach((key) => {
      if (normalized[key]) {
        normalized[key] = normalized[key].map(walk);
      }
    });

    return normalized;
  };

  return { schema: walk(schema), usesObjectId };
}

/**
 * Converts a string to Go PascalCase naming convention.
 * Handles special cases like "id" -> "ID".
 * @param {string} name - The name to convert
 * @returns {string} PascalCase name suitable for Go
 */
function toGoPascalCase(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((part) => {
      const lower = part.toLowerCase();
      if (lower === "id") return "ID";
      if (lower.length === 0) return "";
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join("");
}

/**
 * Maps a JSON schema type to a Go primitive type.
 * @param {object} schema - The schema to map
 * @returns {{type: string, usesObjectId: boolean, usesTime: boolean, isObject: boolean}|null}
 */
function mapPrimitiveType(schema) {
  if (schema.format === "objectId") {
    return {
      type: "primitive.ObjectID",
      usesObjectId: true,
      usesTime: false,
      isObject: false,
    };
  }

  if (schema.format === "date-time") {
    return {
      type: "time.Time",
      usesObjectId: false,
      usesTime: true,
      isObject: false,
    };
  }

  if (Array.isArray(schema.type)) {
    const nonNullTypes = schema.type.filter((type) => type !== "null");
    const uniqueTypes = Array.from(new Set(nonNullTypes));
    if (uniqueTypes.includes("number")) {
      return {
        type: GO_TYPE_MAP.number,
        usesObjectId: false,
        usesTime: false,
        isObject: false,
      };
    }

    if (uniqueTypes.includes("integer") && uniqueTypes.length === 1) {
      return {
        type: GO_TYPE_MAP.integer,
        usesObjectId: false,
        usesTime: false,
        isObject: false,
      };
    }

    if (uniqueTypes.includes("string") && uniqueTypes.length === 1) {
      return {
        type: GO_TYPE_MAP.string,
        usesObjectId: false,
        usesTime: false,
        isObject: false,
      };
    }

    if (uniqueTypes.includes("boolean") && uniqueTypes.length === 1) {
      return {
        type: GO_TYPE_MAP.boolean,
        usesObjectId: false,
        usesTime: false,
        isObject: false,
      };
    }
  }

  const goType = GO_TYPE_MAP[schema.type];
  if (goType) {
    return {
      type: goType,
      usesObjectId: false,
      usesTime: false,
      isObject: false,
    };
  }

  return null;
}

/**
 * Maps a JSON schema type to a BSON type for MongoDB validation.
 * @param {string} type - The JSON schema type
 * @returns {string|undefined}
 */
function mapBsonType(type) {
  return BSON_TYPE_MAP[type];
}

/**
 * Converts a JSON schema to a MongoDB BSON validator schema.
 * Resolves $refs and transforms types to BSON types.
 * @param {object} schema - The JSON schema to convert
 * @returns {object} BSON validator schema
 */
function toBsonValidator(schema) {
  const definitions = {
    ...(schema.$defs || {}),
    ...(schema.definitions || {}),
  };

  const resolveRef = (ref) => {
    const key = ref.split("/").pop();
    const target = definitions[key];
    if (!target) {
      throw new Error(
        `Unable to resolve $ref "${ref}" in schema "${schema.title || "unknown"}". Available definitions: ${Object.keys(definitions).join(", ")}`
      );
    }
    return target;
  };

  const walk = (node, isRoot = false) => {
    if (Array.isArray(node)) return node.map((item) => walk(item, false));
    if (!node || typeof node !== "object") return node;

    const next = { ...node };

    if (next.$ref) {
      const resolved = resolveRef(next.$ref);
      return walk(resolved, false);
    }

    const isObjectId = next.format === "objectId";
    const isDate = next.format === "date-time";

    if (isObjectId) {
      next.bsonType = "objectId";
    } else if (isDate) {
      next.bsonType = "date";
    } else if (Array.isArray(next.type)) {
      const mappedTypes = Array.from(
        new Set(next.type.map(mapBsonType).filter(Boolean))
      );
      if (mappedTypes.length === 1) {
        next.bsonType = mappedTypes[0];
      } else if (mappedTypes.length > 1) {
        next.bsonType = mappedTypes;
      }
    } else if (typeof next.type === "string") {
      const mapped = mapBsonType(next.type);
      if (mapped) next.bsonType = mapped;
    }

    if (isRoot && !next.bsonType) {
      next.bsonType = "object";
    }

    if (next.properties) {
      next.properties = Object.fromEntries(
        Object.entries(next.properties).map(([key, value]) => [
          key,
          walk(value, false),
        ])
      );
    }

    if (next.items) {
      next.items = walk(next.items, false);
    }

    ["$defs", "definitions"].forEach((defKey) => {
      if (next[defKey]) {
        delete next[defKey];
      }
    });

    ["anyOf", "oneOf", "allOf"].forEach((key) => {
      if (next[key]) {
        next[key] = next[key].map((entry) => walk(entry, false));
      }
    });

    delete next.$schema;
    delete next.$id;
    delete next.type;
    delete next.format;
    delete next.tsType;

    return next;
  };

  return walk(schema, true);
}

/**
 * Prepares metadata about schema definitions for Go type generation.
 * @param {object} schema - The JSON schema containing definitions
 * @returns {Map<string, object>} Map of definition key to metadata
 */
function prepareDefinitionInfo(schema) {
  const defs = schema.$defs || schema.definitions || {};
  const defsInfo = new Map();

  for (const [defKey, defSchema] of Object.entries(defs)) {
    const typeName = defSchema.title || toGoPascalCase(defKey);
    const primitive = mapPrimitiveType(defSchema);
    const isObject = !!(defSchema.type === "object" || defSchema.properties);

    defsInfo.set(defKey, {
      defKey,
      schema: defSchema,
      typeName,
      generateStruct: !primitive && isObject,
      mappedType: primitive ? primitive.type : typeName,
      usesObjectId: primitive ? primitive.usesObjectId : false,
      usesTime: primitive ? primitive.usesTime : false,
      isObject: primitive ? primitive.isObject : isObject,
      struct: null,
    });
  }

  return defsInfo;
}

/**
 * Creates type resolution functions for Go code generation.
 * @param {Map<string, object>} defsInfo - Map of schema definitions
 * @returns {{buildStruct: Function, goType: Function}}
 */
function buildGoTypeResolvers(defsInfo) {
  function resolveRef(ref) {
    const match = ref.match(/#\/(?:\$defs|definitions)\/(.+)$/);
    if (!match) {
      throw new Error(`Unsupported $ref format: ${ref}`);
    }

    const defKey = match[1];
    const def = defsInfo.get(defKey);
    if (!def) {
      throw new Error(`Missing definition for ref ${ref}`);
    }

    return def;
  }

  function goType(schema, { required = true } = {}) {
    if (schema.$ref) {
      const refInfo = resolveRef(schema.$ref);
      const baseType = refInfo.generateStruct
        ? refInfo.typeName
        : refInfo.mappedType;
      const type = !required && refInfo.isObject ? `*${baseType}` : baseType;
      return {
        type,
        usesObjectId: refInfo.usesObjectId,
        usesTime: refInfo.usesTime,
        isObject: refInfo.isObject,
      };
    }

    const primitive = mapPrimitiveType(schema);
    if (primitive) {
      return primitive;
    }

    if (schema.type === "array") {
      const inner = goType(schema.items || {}, { required: true });
      return {
        type: `[]${inner.type.replace(/^\*/, "")}`,
        usesObjectId: inner.usesObjectId,
        usesTime: inner.usesTime,
        isObject: false,
      };
    }

    if (schema.type === "object" || schema.properties) {
      const inline = buildInlineStruct(schema);
      const type = required ? inline.type : `*${inline.type}`;
      return {
        type,
        usesObjectId: inline.usesObjectId,
        usesTime: inline.usesTime,
        isObject: true,
      };
    }

    return {
      type: "interface{}",
      usesObjectId: false,
      usesTime: false,
      isObject: false,
    };
  }

  /**
   * Builds field lines for Go struct from schema properties.
   * @param {object} schema - Schema with properties
   * @returns {{lines: string[], usesTime: boolean, usesObjectId: boolean}}
   */
  function buildFieldLines(schema) {
    const requiredSet = new Set(schema.required || []);
    const properties = schema.properties || {};
    const lines = [];
    let usesTime = false;
    let usesObjectId = false;

    for (const [propName, propSchema] of Object.entries(properties)) {
      const isRequired = requiredSet.has(propName);
      const fieldType = goType(propSchema, { required: isRequired });

      usesTime ||= fieldType.usesTime;
      usesObjectId ||= fieldType.usesObjectId;

      const goName = toGoPascalCase(propName);
      // Special fields like _id always use omitempty, or when not required
      const needsOmitEmpty = !isRequired || propName === SPECIAL_FIELDS.ID;
      const tagSuffix = needsOmitEmpty ? ",omitempty" : "";
      const bsonTag = `${propName}${tagSuffix}`;
      const jsonTag = `${propName}${tagSuffix}`;
      lines.push(
        `${goName} ${fieldType.type} \`bson:"${bsonTag}" json:"${jsonTag}"\``
      );
    }

    return { lines, usesTime, usesObjectId };
  }

  function buildInlineStruct(schema) {
    const { lines, usesTime, usesObjectId } = buildFieldLines(schema);
    const type = `struct {\n\t${lines.join("\n\t")}\n}`;
    return { type, usesTime, usesObjectId };
  }

  function buildStruct(typeName, schema) {
    const { lines, usesTime, usesObjectId } = buildFieldLines(schema);
    const struct = `type ${typeName} struct {\n\t${lines.join("\n\t")}\n}`;
    return { struct, usesTime, usesObjectId };
  }

  return { buildStruct, goType };
}

/**
 * Generates Go type definitions from an array of JSON schemas.
 * @param {object[]} schemas - Array of JSON schemas
 * @returns {string} Complete Go source code with type definitions
 */
function generateGoTypes(schemas) {
  let usesTime = false;
  let usesObjectId = false;
  const parts = [];

  for (const schema of schemas) {
    if (!schema.title) {
      throw new Error(
        `Schema is missing required "title" property. Schema: ${JSON.stringify(schema, null, 2).substring(0, 200)}...`
      );
    }

    const defsInfo = prepareDefinitionInfo(schema);
    const { buildStruct } = buildGoTypeResolvers(defsInfo);

    for (const defInfo of defsInfo.values()) {
      if (!defInfo.generateStruct) continue;
      const result = buildStruct(defInfo.typeName, defInfo.schema);
      defInfo.struct = result.struct;
      defInfo.usesObjectId ||= result.usesObjectId;
      defInfo.usesTime ||= result.usesTime;

      usesTime ||= result.usesTime;
      usesObjectId ||= result.usesObjectId;
      parts.push(result.struct);
    }

    const rootResult = buildStruct(schema.title, schema);
    usesTime ||= rootResult.usesTime;
    usesObjectId ||= rootResult.usesObjectId;
    parts.push(rootResult.struct);
  }

  const imports = [];
  if (usesTime) imports.push('"time"');
  if (usesObjectId)
    imports.push('"go.mongodb.org/mongo-driver/bson/primitive"');

  const importBlock = imports.length
    ? `\nimport (\n${imports.map((imp) => `\t${imp}`).join("\n")}\n)\n`
    : "\n";

  return [GO_HEADER, importBlock, parts.join("\n\n"), ""].join("\n");
}

/**
 * Main entry point: reads JSON schemas, generates TypeScript types,
 * Go structs, and BSON validators.
 */
async function run() {
  const schemasDir = path.resolve(process.argv[2] || DEFAULT_SCHEMAS_DIR);
  const generatedFile = path.resolve(process.argv[3] || DEFAULT_TS_OUTPUT);
  const generatedGoFile = path.resolve(process.argv[4] || DEFAULT_GO_OUTPUT);

  const files = fs
    .readdirSync(schemasDir)
    .filter((file) => file.endsWith(".schema.json"))
    .sort((a, b) => a.localeCompare(b, "en"));

  if (!files.length) {
    throw new Error(
      `No schema files (*.schema.json) found in directory: ${schemasDir}. Please ensure schema files exist.`
    );
  }

  let usesObjectId = false;
  const parts = [];
  const schemas = [];

  for (const file of files) {
    const schemaPath = path.join(schemasDir, file);
    const raw = fs.readFileSync(schemaPath, "utf-8");
    const schema = JSON.parse(raw);

    if (!schema.title) {
      throw new Error(
        `Schema file "${file}" is missing required "title" property. This is needed to generate type names.`
      );
    }

    const { schema: normalizedSchema, usesObjectId: schemaUsesObjectId } =
      normalizeSchema(schema);
    usesObjectId = usesObjectId || schemaUsesObjectId;

    const ts = await compile(normalizedSchema, schema.title, {
      bannerComment: "",
    });

    parts.push(ts.trim());
    schemas.push({ file, schema });
  }

  const imports = [];
  if (usesObjectId) {
    imports.push("import { ObjectId } from 'mongodb';");
  }

  const output = [
    HEADER_COMMENT,
    "",
    imports.join("\n"),
    imports.length ? "" : null,
    parts.join("\n\n"),
    "",
  ]
    .filter((line) => line !== null)
    .join("\n");

  fs.mkdirSync(path.dirname(generatedFile), { recursive: true });
  fs.writeFileSync(generatedFile, output, "utf-8");
  execSync(
    `cd ${APP_ROOT} && npm run format -- ${path.relative(APP_ROOT, generatedFile)}`
  );

  console.log(
    `Generated TS types for ${files.length} schemas at ${generatedFile}`
  );

  const goOutput = generateGoTypes(schemas.map((entry) => entry.schema));
  fs.mkdirSync(path.dirname(generatedGoFile), { recursive: true });
  fs.writeFileSync(generatedGoFile, goOutput, "utf-8");
  execSync(`go fmt ${generatedGoFile}`);
  console.log(
    `Generated Go types for ${files.length} schemas at ${generatedGoFile}`
  );

  fs.mkdirSync(DEFAULT_VALIDATORS_DIR, { recursive: true });
  for (const { file, schema } of schemas) {
    const validator = toBsonValidator(schema);
    const outPath = path.join(DEFAULT_VALIDATORS_DIR, file);
    fs.writeFileSync(outPath, JSON.stringify(validator, null, 2), "utf-8");
  }
  console.log(
    `Generated BSON validators for ${files.length} schemas in ${DEFAULT_VALIDATORS_DIR}`
  );
}

// Call to execute async functions in Node.js environment.
(async () => {
  try {
    await run();
  } catch (e) {
    console.error(e);
    process.exit(1);
  }

  process.exit(0);
})();
